### Obter todos os produtos
GET http://localhost:3000/api/produtos
Content-Type: application/json

### Obter um produto por ID
GET http://localhost:3000/api/produtos/1
Content-Type: application/json

### Criar um novo produto### Criar um novo produto
POST http://localhost:3000/api/produtos
Content-Type: application/json

{
  "nome": "Adidads",
  "descricao": "Grand Court 2.0",
  "avaliacao": 5.0,
  "tamanho": 43,
  "cor": "Branco",
  "preco": 259.52,
  "idCategoria": 5
}


### Atualizar um produto por ID
PUT http://localhost:3000/api/produtos/1
Content-Type: application/json

{
  "nome": "Produto Atualizado",
  "preco": 129.90,
  "categoriaId": 2
}

### Deletar um produto por ID
DELETE http://localhost:3000/api/produtos/1
Content-Type: application/json
